name: CI

on: push

env:
    BIOLIB_LOG: debug
    BIOLIB_PROJECT_URI: Protein-Tools/ESM1b-embeddings
    LOCAL_DOCKER_TAG: esm1b-embeddings:latest

jobs:
    build-and-publish:
        name: Build Docker image and publish if on main
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: lfs cache 1
                run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

            -   name: lfs cache 2
                uses: actions/cache@v2
                id: lfs-cache
                with:
                  path: .git/lfs
                  key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1

            -   name: lfs cache 3
                run: git lfs pull

            -   name: Build docker image
                run: docker build -t $LOCAL_DOCKER_TAG .

            -   name: Setup Python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.8.6

            -   name: Install BioLib CLI
                run: pip3 install pybiolib

            -   name: Publish new version to BioLib if on main branch
                if: ${{ github.ref == 'refs/heads/main' }}
                run: biolib push $BIOLIB_PROJECT_URI --path biolib
                env:
                    BIOLIB_TOKEN: ${{ secrets.BIOLIB_TOKEN }}
